### ISSUE TITLE
Fails to run when parcel-bundler is installed globally

### ISSUE THREAD

**Issue by helenarobotics** [dobesv/parcel-plugin-assets-list#8]
The plugin fails to run properly if parcel is installed globally (per the docs) https://github.com/parcel-bundler/parcel
```
npm install -g parcel-bundler
```
The error generated is:
```
 Plugin parcel-plugin-assets-list failed to initialize: Error: Cannot find module 'parcel-bundler/src/packagers/Packager'
...
```
If the parcel is installed both globally and in the package (to try and workaround the above error), then a different error is generated.
```
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
```

**Comment by dobesv** [comment]
I wonder if it would work if the packager files used:

```
const Packager = require('parcel-bundler').Packager;
```

instead of

```
const Packager = require('parcel-bundler/src/packagers/Packager');
```

You could try making the change in your node_modules folder and see if it fixes your issue.  Otherwise I'm not quite sure what would fix it.

If that does the trick I don't mind updating this to use that import method.  TBH I'm not sure why I import it the way I do right now, it looks weird.

**Comment by helenarobotics** [comment]
``` Plugin parcel-plugin-assets-list failed to initialize: Error: Cannot find module 'parcel-bundler'```

Will try a couple more iterations to see if I can find something that works.

[ Note, I'm not a front-end/Javascript developer, so I'm a bit lost, but a long-time programmer, so I'm just making intelligent guesses. ]

**Comment by dobesv** [comment]
Hmm I wonder if this can even work with `parcel-bundler` globally installed.  The plugin has to import some things from `parcel-bundler` in order to function.  Looking at https://stackoverflow.com/questions/15636367/nodejs-require-a-global-module-package I see that normally packages in a folder cannot import from a globally installed module.

**Comment by helenarobotics** [comment]
I attempted an 'npm link parcel-bundler', but it also failed.  For now, I'm going to try another direction, given my lack of knowledge about parcel plugins.

**Comment by dobesv** [comment]
Sure.  I don't personally see how to make this work well with a globally installed `parcel-bundler`.  I think they messed up by making that the suggested way to install parcel.
